// Charakter-Pools pro Fandom.
// Jedes Fandom braucht MINDESTENS 40 Charaktere, damit die Auswahl sauber funktioniert.
// "id" muss innerhalb eines Fandoms eindeutig sein. "img" zeigt auf dein Bilder-Verzeichnis.
//
// -> Einfach hier für jedes Fandom die echten Charaktere eintragen.
// Platzhalter-Einträge sind bereits als Beispiel für "acnh" vorbereitet (40 Stück).

const CHARACTER_POOLS = {
    acnh: [
        { id: "acnh_tom_nook", name: "Tom Nook", img: "img/tomnook.jpg" },
        { id: "acnh_tom_nook", name: "Tom Nook", img: "img/tomnook.jpg" },
        { id: "acnh_tom_nook", name: "Tom Nook", img: "img/tomnook.jpg" },
        { id: "acnh_tom_nook", name: "Tom Nook", img: "img/tomnook.jpg" },
        { id: "acnh_tom_nook", name: "Tom Nook", img: "img/tomnook.jpg" },
        { id: "acnh_tom_nook", name: "Tom Nook", img: "img/tomnook.jpg" },
        { id: "acnh_tom_nook", name: "Tom Nook", img: "img/tomnook.jpg" },
        { id: "acnh_tom_nook", name: "Tom Nook", img: "img/tomnook.jpg" },
        { id: "acnh_tom_nook", name: "Tom Nook", img: "img/tomnook.jpg" },
        { id: "acnh_tom_nook", name: "Tom Nook", img: "img/tomnook.jpg" },
        { id: "acnh_tom_nook", name: "Tom Nook", img: "img/tomnook.jpg" },
        { id: "acnh_tom_nook", name: "Tom Nook", img: "img/tomnook.jpg" },
        { id: "acnh_tom_nook", name: "Tom Nook", img: "img/tomnook.jpg" },
        { id: "acnh_tom_nook", name: "Tom Nook", img: "img/tomnook.jpg" },
        { id: "acnh_tom_nook", name: "Tom Nook", img: "img/tomnook.jpg" },
        { id: "acnh_tom_nook", name: "Tom Nook", img: "img/tomnook.jpg" },
        { id: "acnh_tom_nook", name: "Tom Nook", img: "img/tomnook.jpg" },
        { id: "acnh_tom_nook", name: "Tom Nook", img: "img/tomnook.jpg" },
        { id: "acnh_tom_nook", name: "Tom Nook", img: "img/tomnook.jpg" },
        { id: "acnh_tom_nook", name: "Tom Nook", img: "img/tomnook.jpg" },
        { id: "acnh_tom_nook", name: "Tom Nook", img: "img/tomnook.jpg" },
        { id: "acnh_tom_nook", name: "Tom Nook", img: "img/tomnook.jpg" },
        { id: "acnh_tom_nook", name: "Tom Nook", img: "img/tomnook.jpg" },
        { id: "acnh_tom_nook", name: "Tom Nook", img: "img/tomnook.jpg" },
        { id: "acnh_tom_nook", name: "Tom Nook", img: "img/tomnook.jpg" },
        { id: "acnh_tom_nook", name: "Tom Nook", img: "img/tomnook.jpg" },
        { id: "acnh_tom_nook", name: "Tom Nook", img: "img/tomnook.jpg" },
        { id: "acnh_tom_nook", name: "Tom Nook", img: "img/tomnook.jpg" },
        { id: "acnh_tom_nook", name: "Tom Nook", img: "img/tomnook.jpg" },
        { id: "acnh_tom_nook", name: "Tom Nook", img: "img/tomnook.jpg" },
        { id: "acnh_tom_nook", name: "Tom Nook", img: "img/tomnook.jpg" },
        { id: "acnh_tom_nook", name: "Tom Nook", img: "img/tomnook.jpg" },
        { id: "acnh_tom_nook", name: "Tom Nook", img: "img/tomnook.jpg" },
        { id: "acnh_tom_nook", name: "Tom Nook", img: "img/tomnook.jpg" },
        { id: "acnh_tom_nook", name: "Tom Nook", img: "img/tomnook.jpg" },
        { id: "acnh_tom_nook", name: "Tom Nook", img: "img/tomnook.jpg" },
        { id: "acnh_tom_nook", name: "Tom Nook", img: "img/tomnook.jpg" },
        { id: "acnh_tom_nook", name: "Tom Nook", img: "img/tomnook.jpg" },
        { id: "acnh_tom_nook", name: "Tom Nook", img: "img/tomnook.jpg" },
        { id: "acnh_tom_nook", name: "Tom Nook", img: "img/tomnook.jpg" },
        { id: "acnh_tom_nook", name: "Tom Nook", img: "img/tomnook.jpg" },
        { id: "acnh_tom_nook", name: "Tom Nook", img: "img/tomnook.jpg" },
        { id: "acnh_tom_nook", name: "Tom Nook", img: "img/tomnook.jpg" },
    ],

    disney: Array.from({ length: 45 }, (_, i) => ({
        id: `disney_${i + 1}`,
        name: `Charakter ${i + 1}`,
        img: `img/disney/character_${i + 1}.jpg`
    })),

    genshin: [
        { id: "genshin_keqing", name: "Keqing", img: "img/keqing.jpg" },
        { id: "genshin_qiqi", name: "Qiqi", img: "img/qiqi.jpg" },
        { id: "genshin_chongyun", name: "Chongyun", img: "img/chongyun.jpg" },
        { id: "genshin_xingqiu", name: "Xingqiu", img: "img/xingqiu.jpg" },
        { id: "genshin_xiangling", name: "Xiangling", img: "img/xiangling.jpg" },
        { id: "genshin_ningguang", name: "Ningguang", img: "img/ningguang.jpg" },
        { id: "genshin_mona", name: "Mona", img: "img/mona.jpg" },
        { id: "genshin_sucrose", name: "Sucrose", img: "img/sucrose.jpg" },
        { id: "genshin_fischl", name: "Fischl", img: "img/fischl.jpg" },
        { id: "genshin_noelle", name: "Noelle", img: "img/noelle.jpg" },
        { id: "genshin_bennett", name: "Bennett", img: "img/bennett.jpg" },
        { id: "genshin_klee", name: "Klee", img: "img/klee.jpg" },
        { id: "genshin_venti", name: "Venti", img: "img/venti.jpg" },
        { id: "genshin_razor", name: "Razor", img: "img/razor.jpg" },
        { id: "genshin_diluc", name: "Diluc", img: "img/diluc.png" },
        { id: "genshin_barbara", name: "Barbara", img: "img/barbara.jpg" },
        { id: "genshin_kaeya", name: "Kaeya", img: "img/kaeya.jpg" },
        { id: "genshin_lisa", name: "Lisa", img: "img/lisa.jpg" },
        { id: "genshin_amber", name: "Amber", img: "img/amber.jpg" },
        { id: "genshin_jean", name: "Jean", img: "img/jean.jpg" },
        { id: "genshin_lumine", name: "Lumine", img: "img/lumine.jpg" },
        { id: "genshin_aether", name: "Aether", img: "img/aether.jpg" },
        { id: "genshin_xinyan", name: "Xinyan", img: "img/xinyan.jpg" },
        { id: "genshin_diano", name: "Diona", img: "img/diana.jpg" },
        { id: "genshin_zhongli", name: "Zhongli", img: "img/zhongli.jpg" },
        { id: "genshin_childe", name: "Childe", img: "img/childe.jpg" },
        { id: "genshin_albedo", name: "Albedo", img: "img/albedo.jpg" },
        { id: "genshin_ganyu", name: "Ganyu", img: "img/ganyu.jpg" },
        { id: "genshin_hutao", name: "Hu Tao", img: "img/hutao.jpg" },
        { id: "genshin_xiao", name: "Xiao", img: "img/xiao.jpg" },
        { id: "genshin_rosaria", name: "Rosaria", img: "img/rosaria.jpg" },
        { id: "genshin_eula", name: "Eula", img: "img/eula.jpg" },
        { id: "genshin_yanfei", name: "Yanfei", img: "img/yanfei.jpg" },
        { id: "genshin_kazuha", name: "Kazuha", img: "img/kazuha.jpg" },
        { id: "genshin_sayu", name: "Sayu", img: "img/sayu.jpg" },
        { id: "genshin_yoimiya", name: "Yoimiya", img: "img/yoimiya.jpg" },
        { id: "genshin_ayaka", name: "Ayaka", img: "img/ayaka.jpg" },
        { id: "genshin_aloy", name: "Aloy", img: "img/aloy.jpg" },
        { id: "genshin_kokomi", name: "Kokomi", img: "img/kokomi.jpg" },
        { id: "genshin_raiden", name: "Raiden", img: "img/raiden.jpg" },
        { id: "genshin_sara", name: "Sara", img: "img/sara.jpg" },
        { id: "genshin_thoma", name: "Thoma", img: "img/thoma.jpg" },
        { id: "genshin_itto", name: "Itto", img: "img/itto.jpg" },
        { id: "genshin_gorou", name: "gorou", img: "img/gorou.jpg" },
        { id: "genshin_yunjin", name: "Yun Jin", img: "img/yunjin.jpg" },
        { id: "genshin_shenhe", name: "Shenhe", img: "img/shenhe.jpg" },
        { id: "genshin_yaemiko", name: "Yae Miko", img: "img/yaemiko.jpg" },
        { id: "genshin_ayato", name: "Ayato", img: "img/ayato.jpg" },
        { id: "genshin_yelan", name: "Yelan", img: "img/yelan.jpg" },
        { id: "genshin_shinobu", name: "Shinobu", img: "img/shinobu.jpg" },
        { id: "genshin_heizou", name: "Heizou", img: "img/heizou.jpg" },
        { id: "genshin_dori", name: "Dori", img: "img/dori.jpg" },
        { id: "genshin_collei", name: "Collei", img: "img/collei.jpg" },
        { id: "genshin_tighnari", name: "Tighnari", img: "img/tighnari.jpg" },
        { id: "genshin_candace", name: "Candace", img: "img/candace.jpg" },
        { id: "genshin_nilou", name: "Nilou", img: "img/nilou.png" },
        { id: "genshin_cyno", name: "Cyno", img: "img/cyno.jpg" },
        { id: "genshin_layla", name: "Layla", img: "img/layla.jpg" },
        { id: "genshin_nahida", name: "Nahida", img: "img/nahida.jpg" },
        { id: "genshin_faruzan", name: "Faruzan", img: "img/faruzan.jpg" },
        { id: "genshin_scara", name: "Wanderer", img: "img/scara.jpg" },
        { id: "genshin_yaoyao", name: "Yaoyao", img: "img/yaoyao.jpg" },
        { id: "genshin_alhaitham", name: "Alhaitham", img: "img/alhaitham.jpg" },
        { id: "genshin_mika", name: "Mika", img: "img/mika.jpg" },
        { id: "genshin_dehya", name: "Dehya", img: "img/dehya.jpg" },
        { id: "genshin_kaveh", name: "Kaveh", img: "img/kaveh.jpg" },
        { id: "genshin_baizhu", name: "Baizhu", img: "img/baizhu.jpg" },
        { id: "genshin_kirara", name: "Kirara", img: "img/kirara.jpg" },
        { id: "genshin_freminet", name: "Freminet", img: "img/freminet.jpg" },
        { id: "genshin_lyney", name: "Lyney", img: "img/lyney.jpg" },
        { id: "genshin_lynette", name: "Lynette", img: "img/lynette.jpg" },
        { id: "genshin_neuvi", name: "Neuvillette", img: "img/neuvi.jpg" },
        { id: "genshin_wrio", name: "Wriothesley", img: "img/wrio.jpg" },
        { id: "genshin_furina", name: "Furina", img: "img/furina.jpg" },
        { id: "genshin_charlotte", name: "Charlotte", img: "img/charlotte.jpg" },
        { id: "genshin_chevreuse", name: "Chevreuse", img: "img/chevreuse.jpg" },
        { id: "genshin_navia", name: "Navia", img: "img/navia.jpg" },
        { id: "genshin_gaming", name: "Gaming", img: "img/gaming.jpg" },
        { id: "genshin_xianyun", name: "Xianyun", img: "img/xianyun.jpg" },
        { id: "genshin_chiori", name: "Chiori", img: "img/chiori.png" },
        { id: "genshin_arlecchino", name: "Arlecchino", img: "img/arlecchino.jpg" },
        { id: "genshin_sethos", name: "Sethos", img: "img/sethos.jpg" },
        { id: "genshin_clorinde", name: "Clorinde", img: "img/clorinde.jpg" },
        { id: "genshin_sigewinne", name: "Sigewinne", img: "img/sigewinne.jpg" },
        { id: "genshin_emilie", name: "Emilie", img: "img/emilie.jpg" },
        { id: "genshin_kinich", name: "Kinich", img: "img/kinich.jpg" },
        { id: "genshin_kachina", name: "Kachina", img: "img/kachina.jpg" },
        { id: "genshin_mualani", name: "Mualani", img: "img/mualani.jpg" },
        { id: "genshin_xilonen", name: "Xilonen", img: "img/xilonen.jpg" },
        { id: "genshin_ororon", name: "Ororon", img: "img/ororon.jpg" },
        { id: "genshin_chasca", name: "Chasca", img: "img/chasca.jpg" },
        { id: "genshin_lanyan", name: "Lan Yan", img: "img/lanyan.jpg" },
        { id: "genshin_mavuika", name: "Mavuika", img: "img/mavuika.jpg" },
        { id: "genshin_citlali", name: "Citlali", img: "img/citlali.jpg" },
        { id: "genshin_mizuki", name: "Mizuki", img: "img/mizuki.jpg" },
        { id: "genshin_varesa", name: "Varesa", img: "img/varesa.jpg" },
        { id: "genshin_iansan", name: "Iansan", img: "img/iansan.jpg" },
        { id: "genshin_escoffier", name: "Escoffier", img: "img/escoffier.jpg" },
        { id: "genshin_ifa", name: "Ifa", img: "img/ifa.jpg" },
        { id: "genshin_dahlia", name: "Dahlia", img: "img/dahlia.jpg" },
        { id: "genshin_skirk", name: "Skirk", img: "img/skirk.jpg" },
        { id: "genshin_ineffa", name: "Ineffa", img: "img/ineffa.jpg" },
        { id: "genshin_flins", name: "Flins", img: "img/flins.jpg" },
        { id: "genshin_lauma", name: "Lauma", img: "img/lauma.jpg" },
        { id: "genshin_aino", name: "Aino", img: "img/aino.png" },
        { id: "genshin_nefer", name: "Nefer", img: "img/nefer.jpg" },
        { id: "genshin_durin", name: "Durin", img: "img/durin.jpg" },
        { id: "genshin_jahoda", name: "Jahoda", img: "img/jahoda.jpg" },
        { id: "genshin_zibai", name: "Zibai", img: "img/zibai.jpg" },
        { id: "genshin_illuga", name: "Illuga", img: "img/illuga.jpg" },
        { id: "genshin_columbina", name: "Columbina", img: "img/columbina.jpg" },
        { id: "genshin_varka", name: "Varka", img: "img/varka.jpg" },
        { id: "genshin_linnea", name: "Linnea", img: "img/linnea.jpg" },
        { id: "genshin_prune", name: "Prune", img: "img/prune.jpg" },
        { id: "genshin_lohen", name: "Lohen", img: "img/lohen.jpg" },
        { id: "genshin_nicole", name: "Nicole", img: "img/nicole.jpg" },
        { id: "genshin_sandrone", name: "Sandrone", img: "img/sandrone.jpg" },
        { id: "genshin_alice", name: "Alice", img: "img/alice.jpg" },
        { id: "genshin_alyosha", name: "Alyosha", img: "img/alyosha.jpg" },
        { id: "genshin_capitano", name: "Capitano", img: "img/capitano.jpg" },
        { id: "genshin_dainsleif", name: "Dainsleif", img: "img/dainsleif.jpg" },
        { id: "genshin_danica", name: "Danica", img: "img/danica.jpg" },
        { id: "genshin_dottore", name: "Dottore", img: "img/dottore.jpg" },
        { id: "genshin_mitya", name: "Mitya", img: "img/mitya.jpg" },
        { id: "genshin_noy", name: "Noy", img: "img/noy.jpg" },
        { id: "genshin_odette", name: "Odette", img: "img/odette.jpg" },
        { id: "genshin_pantalone", name: "Pantalone", img: "img/pantalone.jpg" },
        { id: "genshin_pierro", name: "Pierro", img: "img/pierro.jpg" },
        { id: "genshin_pulcinella", name: "Pulcinella", img: "img/pulcinella.jpg" },
        { id: "genshin_rerir", name: "Rerir", img: "img/rerir.jpg" },
        { id: "genshin_tsaritsa", name: "Tsaritsa", img: "img/tsaritsa.jpg" },
        { id: "genshin_valeriy", name: "Valeriy", img: "img/valeriy.jpg" },
        { id: "genshin_vesna", name: "Vesna", img: "img/vesna.jpg" },
        { id: "genshin_vodyanitsa", name: "Vodyanitsa", img: "img/vodyanitsa.jpg" },
        { id: "genshin_paimon", name: "Paimon", img: "img/paimon.jpg" },
        { id: "genshin_god", name: "God", img: "img/god.jpg" },
        { id: "genshin_timmie", name: "Timmie", img: "img/timmie.jpg" },
        { id: "genshin_katheryne", name: "Katheryne", img: "img/katheryne.jpg" },
        { id: "genshin_signora", name: "La Signora", img: "img/signora.jpg" },
    ],

    mlbb: Array.from({ length: 45 }, (_, i) => ({
        id: `mlbb_${i + 1}`,
        name: `Charakter ${i + 1}`,
        img: `img/mlbb/character_${i + 1}.jpg`
    })),

    mha: Array.from({ length: 45 }, (_, i) => ({
        id: `mha_${i + 1}`,
        name: `Charakter ${i + 1}`,
        img: `img/mha/character_${i + 1}.jpg`
    })),

    pokemon: Array.from({ length: 45 }, (_, i) => ({
        id: `pokemon_${i + 1}`,
        name: `Charakter ${i + 1}`,
        img: `img/pokemon/character_${i + 1}.jpg`
    }))
};

const BOARD_SIZE = 30;